### PR TITLE
All downloads

### PR DESCRIPTION
**Pull request by muffato**
First version of a pipeline that can download repeat-masking and gene annotations from Ensembl.

Typical output:
```
[2e/5c1cb7] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:DOWNLOAD:ENSEMBL_GENESET_DOWNLOAD (GCA_907164935.1|2021_11)          [100%] 1 of 1 ✔
[8c/86a437] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:DOWNLOAD:ENSEMBL_GENOME_DOWNLOAD (GCA_907164935.1)                   [100%] 1 of 1 ✔
[c4/9aff6e] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_GENES_FASTA:TABIX_BGZIP (GCA_907164935.1.ensembl.2021_11.... [100%] 3 of 3 ✔
[f7/52d929] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_GENES_FASTA:CUSTOM_GETCHROMSIZES (GCA_907164935.1.ensembl... [100%] 3 of 3 ✔
[1d/5d6fd3] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_GENES_FASTA:SAMTOOLS_DICT (Osmia_bicornis_bicornis-GCA_90... [100%] 3 of 3 ✔
[5b/55f570] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_GFF:TABIX_SORT_BGZIP (Osmia_bicornis_bicornis-GCA_9071649... [100%] 1 of 1 ✔
[d3/6e0e25] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_GFF:TABIX_TABIX_CSI (GCA_907164935.1.ensembl.2021_11)        [100%] 1 of 1 ✔
[7a/053c99] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_GFF:TABIX_TABIX_TBI (GCA_907164935.1.ensembl.2021_11)        [100%] 1 of 1 ✔
[c1/c2c0bd] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEAT_MASKED_FASTA:TABIX_BGZIP (GCA_907164935.1.masked.e... [100%] 1 of 1 ✔
[a6/39b73e] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEAT_MASKED_FASTA:CUSTOM_GETCHROMSIZES (GCA_907164935.1... [100%] 1 of 1 ✔
[37/d30a5a] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEAT_MASKED_FASTA:SAMTOOLS_DICT (GCA_907164935.1.masked... [100%] 1 of 1 ✔
[eb/d46e10] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEATS:REPEATS_BED (GCA_907164935.1.masked.ensembl.fa)      [100%] 1 of 1 ✔
[b2/50b374] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEATS:TABIX_BGZIP (GCA_907164935.1.masked.ensembl)         [100%] 1 of 1 ✔
[8d/e150a0] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEATS:TABIX_TABIX_CSI (GCA_907164935.1.masked.ensembl)     [100%] 1 of 1 ✔
[f3/debda6] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:PREPARE_REPEATS:TABIX_TABIX_TBI (GCA_907164935.1.masked.ensembl)     [100%] 1 of 1 ✔
[a4/74c598] process > SANGERTOL_ENSEMBLDOWNLOAD:ENSEMBLDOWNLOAD:CUSTOM_DUMPSOFTWAREVERSIONS (1)                                      [100%] 1 of 1 ✔

```

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/ensembldownload/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
The first thing I would like feedback on, @priyanka-surana, is the configuration of this pipeline. I was hoping I could find something sensible, but I'm still not happy with the way it works.
Essentially, the pipeline needs to download two products: repeat annotations and gene annotations, and there is nothing in common between them.

I find the current solution very hacky.

1. The [samplesheet](https://github.com/sanger-tol/ensembldownload/blob/all_downloads/assets/samplesheet.csv) has an optional `geneset_version` column. When empty, the pipeline interprets that as "download the repeat annotations
2. The [download subworkflow](https://github.com/sanger-tol/ensembldownload/blob/all_downloads/subworkflows/local/download.nf#L18-L45) separates the two cases into different download modules and different output channels
3. The [main workflow](https://github.com/sanger-tol/ensembldownload/blob/all_downloads/workflows/ensembldownload.nf#L96-L114) joins each output channel to a different subworkflow for processing

Maybe I didn't want to admit it to myself ... Should this be two pipelines ?

**Comment by muffato** [comment]
An alternative could be that only the gene annotation is explicitly requested, and the repeat annotation is implicitly added for these genomes. The justification would be that Ensembl can't annotate the genes without first repeat-masking the genome. 

It means we would miss cases where only the repeat annotation is available. Not sure that can happen in practice

**Comment by priyanka-surana** [comment]
Are you splitting this into 2 pipelines?

**Comment by muffato** [comment]
Yes. I'll close this PR for now

**Pull request closed without merging**
